if(EXISTS "${CMAKE_ROOT}/Modules/CPack.cmake")
set(CPACK_set_DESTDIR "on")

set(UBITRACK_PACKAGE_VERSION "${UBITRACK_VERSION_MAJOR}.${UBITRACK_VERSION_MINOR}.${UBITRACK_VERSION_PATCH}")
set(UBITRACK_RUNTIME_SUFFIX "")
  if(MSVC_VERSION EQUAL 1400)
    set(UBITRACK_RUNTIME_SUFFIX -vc8)
  elseif(MSVC_VERSION EQUAL 1500)
    set(UBITRACK_RUNTIME_SUFFIX -vc9)
  elseif(MSVC_VERSION EQUAL 1600)
    set(UBITRACK_RUNTIME_SUFFIX -vc10)
  elseif(MSVC_VERSION EQUAL 1700)
    set(UBITRACK_RUNTIME_SUFFIX -vc11)
  elseif(MSVC_VERSION EQUAL 1800)
    set(UBITRACK_RUNTIME_SUFFIX -vc12)
  elseif(MSVC_VERSION EQUAL 1900)
    set(UBITRACK_RUNTIME_SUFFIX -vc14)
  endif()




if(NOT UBITRACK_CUSTOM_PACKAGE_INFO)
  set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Ubitrack Tracking and Sensor Fusion")
  set(CPACK_PACKAGE_DESCRIPTION
"Ubitrack is an open source tracking and sensor fusion software library. ")
  set(CPACK_PACKAGE_VENDOR "OpenCV Foundation")
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
  set(CPACK_PACKAGE_CONTACT "no-reply@tum.de")
  set(CPACK_PACKAGE_VERSION_MAJOR "${UBITRACK_VERSION_MAJOR}")
  set(CPACK_PACKAGE_VERSION_MINOR "${UBITRACK_VERSION_MINOR}")
  set(CPACK_PACKAGE_VERSION_PATCH "${UBITRACK_VERSION_PATCH}")
  set(CPACK_PACKAGE_VERSION "${UBITRACK_PACKAGE_VERSION}")
endif(NOT UBITRACK_CUSTOM_PACKAGE_INFO)

#arch
if(X86)
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "i386")
  set(CPACK_RPM_PACKAGE_ARCHITECTURE "i686")
elseif(X86_64)
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
  set(CPACK_RPM_PACKAGE_ARCHITECTURE "x86_64")
elseif(ARM)
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "armhf")
  set(CPACK_RPM_PACKAGE_ARCHITECTURE "armhf")
elseif(AARCH64)
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "arm64")
  set(CPACK_RPM_PACKAGE_ARCHITECTURE "aarch64")
else()
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR})
  set(CPACK_RPM_PACKAGE_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR})
endif()

if(CPACK_GENERATOR STREQUAL "DEB")
  set(UBITRACK_PACKAGE_ARCH_SUFFIX ${CPACK_DEBIAN_PACKAGE_ARCHITECTURE})
elseif(CPACK_GENERATOR STREQUAL "RPM")
  set(UBITRACK_PACKAGE_ARCH_SUFFIX ${CPACK_RPM_PACKAGE_ARCHITECTURE})
else()
  set(UBITRACK_PACKAGE_ARCH_SUFFIX ${CMAKE_SYSTEM_PROCESSOR})
endif()

set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${UBITRACK_PACKAGE_VERSION}-${UBITRACK_PACKAGE_ARCH_SUFFIX}${UBITRACK_RUNTIME_SUFFIX}")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${UBITRACK_PACKAGE_VERSION}-${UBITRACK_PACKAGE_ARCH_SUFFIX}${UBITRACK_RUNTIME_SUFFIX}")

#rpm options
set(CPACK_RPM_COMPONENT_INSTALL TRUE)
set(CPACK_RPM_PACKAGE_SUMMARY ${CPACK_PACKAGE_DESCRIPTION_SUMMARY})
set(CPACK_RPM_PACKAGE_DESCRIPTION ${CPACK_PACKAGE_DESCRIPTION})
set(CPACK_RPM_PACKAGE_URL "https://github.com/Ubitrack")
set(CPACK_RPM_PACKAGE_LICENSE "LGPL")

#deb options
set(CPACK_DEB_COMPONENT_INSTALL TRUE)
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_SECTION "libs")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/Ubitrack")

#display names
set(CPACK_COMPONENT_DEV_DISPLAY_NAME     "Development files")
set(CPACK_COMPONENT_DOCS_DISPLAY_NAME    "Documentation")
set(CPACK_COMPONENT_LIBS_DISPLAY_NAME    "Libraries and data")
set(CPACK_COMPONENT_JAVA_DISPLAY_NAME    "Java bindings")
set(CPACK_COMPONENT_DOTNET_DISPLAY_NAME  "Dotnet bindings")
set(CPACK_COMPONENT_APPS_DISPLAY_NAME    "Applications")

#depencencies
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS TRUE)
set(CPACK_COMPONENT_LIBS_REQUIRED TRUE)
set(CPACK_COMPONENT_DEV_DEPENDS libs)
set(CPACK_COMPONENT_DOCS_DEPENDS libs)
set(CPACK_COMPONENT_JAVA_DEPENDS libs)
set(CPACK_COMPONENT_DOTNET_DEPENDS libs)
set(CPACK_COMPONENT_APPS_DEPENDS libs)


if(NOT UBITRACK_CUSTOM_PACKAGE_INFO)
  set(CPACK_COMPONENT_LIBS_DESCRIPTION "Ubitrack Library")
  set(CPACK_DEBIAN_COMPONENT_LIBS_NAME "lib${CMAKE_PROJECT_NAME}")

  set(CPACK_COMPONENT_DOTNET_DESCRIPTION "Dotnet bindings for Ubitrack Library")
  set(CPACK_DEBIAN_COMPONENT_DOTNET_NAME "lib${CMAKE_PROJECT_NAME}-dotnet")

  set(CPACK_COMPONENT_JAVA_DESCRIPTION "Java bindings for Ubitrack Library")
  set(CPACK_DEBIAN_COMPONENT_JAVA_NAME "lib${CMAKE_PROJECT_NAME}-java")

  set(CPACK_COMPONENT_DEV_DESCRIPTION "Development files for Ubitrack Library")
  set(CPACK_DEBIAN_COMPONENT_DEV_NAME "lib${CMAKE_PROJECT_NAME}-dev")

  set(CPACK_COMPONENT_DOCS_DESCRIPTION "Documentation for Ubitrack Library")
  set(CPACK_DEBIAN_COMPONENT_DOCS_NAME "lib${CMAKE_PROJECT_NAME}-docs")

  set(CPACK_COMPONENT_SAMPLES_DESCRIPTION "Samples for Ubitrack Library")
  set(CPACK_DEBIAN_COMPONENT_SAMPLES_NAME "lib${CMAKE_PROJECT_NAME}-samples")

  set(CPACK_COMPONENT_APPS_DESCRIPTION "Applications for Ubitrack Library")
  set(CPACK_DEBIAN_COMPONENT_APPS_NAME "lib${CMAKE_PROJECT_NAME}-apps")
endif(NOT UBITRACK_CUSTOM_PACKAGE_INFO)

include(CPack)

ENDif(EXISTS "${CMAKE_ROOT}/Modules/CPack.cmake")