git clone https://github.com/Ubitrack/utcore.git modules/utcore
git clone https://github.com/Ubitrack/utvision.git modules/utvision
git clone https://github.com/Ubitrack/utdataflow.git modules/utdataflow
git clone https://github.com/Ubitrack/utfacade.git modules/utfacade
git clone https://github.com/Ubitrack/utvisualization.git modules/utvisualization
git clone https://github.com/Ubitrack/component_core.git modules/component_core
git clone https://github.com/Ubitrack/component_vision.git modules/component_vision
git clone https://github.com/Ubitrack/component_visualization.git modules/component_visualization
git clone https://github.com/Ubitrack/device_camera_directshow.git modules/device_camera_directshow
git clone https://github.com/Ubitrack/device_camera_flycapture.git modules/device_camera_flycapture
git clone https://github.com/Ubitrack/device_tracker_art.git modules/device_tracker_art
git clone https://github.com/Ubitrack/device_comm_zmq.git modules/device_comm_zmq
git clone https://github.com/Ubitrack/device_camera_kinect2.git modules/device_camera_kinect2