git submodule add git@intern.far.in.tum.de:Ubitrack/utCore.git modules/utcore
git submodule add git@intern.far.in.tum.de:Ubitrack/utVision.git modules/utvision
git submodule add git@intern.far.in.tum.de:Ubitrack/utComponents.git modules/utcomponents
git submodule add git@intern.far.in.tum.de:Ubitrack/utVisionComponents.git modules/utvisioncomponents
git submodule add git@intern.far.in.tum.de:Ubitrack/utDataflow.git modules/utdataflow
git submodule add git@intern.far.in.tum.de:Ubitrack/utFacade.git modules/utfacade
git submodule add git@intern.far.in.tum.de:Ubitrack/utVisualization.git modules/utvisualization
git submodule add git@intern.far.in.tum.de:UbitrackContrib/DirectShowDriver.git modules/mswindows
git submodule add git@intern.far.in.tum.de:UbitrackContrib/ARTDriver.git modules/artdriver